# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-AuthPOP3
version:      0.02
version_from: lib/Apache/AuthPOP3.pm
installdirs:  site
requires:
    Cache::Cache:                  0
    Digest::SHA1:                  0
    Net::POP3:                     0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
